불규칙동사 변형 퀴즈 추가
Heavybros/PythonStudy pull request #12
Opened 2019-12-26 14:30 UTC by flagman1211

파이썬 파일 작업 중...

2019-12-26 14:33 UTC, flagman1211 commented
여기에 아무거나 쓰면 되는건가

2019-12-26 14:36 UTC, flagman1211 commented
111

2019-12-26 15:14 UTC, HaenaraShin requested changes
README의 풀어볼 문제 목록에 추가 부탁해.
오탈자도 같이 수정 해줘

2019-12-26 15:14 UTC, HaenaraShin commented on IrregularVerbs/IrregularVerbs.md
> +- 일일히 입력하기 번거롭다. 그럼으로 파일의 이름을 입력 받아 해당 파일의 내용을 읽기로 한다.
별건 아니지만 '그럼으로' 를 '그러므로'로 오탈자 수정부탁해

2019-12-27 13:03 UTC, closed without merging

2019-12-27 17:32 UTC, HaenaraShin commented
PR 닫지말고 여기에 추가 수정해서 올려줘도 돼 ㅋㅋ